# Site settings
author: industrious-generator-6081
title: 
header-img: img/home-bg.png
email: graywolf.niehaus@live.com
copyright_name: industrious-generator-6081
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  blackgraywolf

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
